version: '3.3'

services:
    db:
        image: postgres
        container_name: budgets
        restart: always
        volumes:
            - ./tmp/pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=budgets
            - POSTGRES_PASSWORD=budgets
            - POSTGRES_DB=budgets
        ports:
            - 5432:5432
